[package]
name = "followermaze"
version = "0.1.0"
authors = ["João Oliveira <hello@jxs.pt>"]
edition = "2018"

[lib]
name = "followermaze"
path = "src/lib/mod.rs"

[dependencies]
tokio = "0.1.18"
futures = "0.1.25"
log = "0.4.2"
env_logger = "0.5.10"
bytes = "0.4.12"
failure = "0.1.5"

[profile.release]
debug = true
