[package]
name = "followermaze"
version = "0.1.0"
authors = ["João Oliveira <hello@jxs.pt>"]
edition = "2018"

[lib]
name = "followermaze"
path = "src/lib/mod.rs"

[dependencies]
tokio = {git = "https://github.com/tokio-rs/tokio.git", rev = "a18ddb3b616b8c4c910fc927f6d72272319675c2"}
log = "0.4.2"
env_logger = "0.5.10"
bytes = "0.4.12"
failure = "0.1.5"
futures-preview = {version = "0.3.0-alpha.17", features = ["nightly", "async-await"]}



[profile.release]
debug = true
