[package]
name = "followermaze"
version = "0.1.0"
authors = ["João Oliveira <hello@jxs.pt>"]

[lib]
name = "followermaze"
path = "src/lib/mod.rs"

[dependencies]
# tokio = "0.1.7"
tokio = "0.1.8"
futures = "0.1.20"
log = "0.4.2"
env_logger = "0.5.10"

[profile.release]
debug = true
